name: Deploy package to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update version in pyproject.toml from current git tag
        run: >-
          sed -i "s/0\\.0\\.0\\.dev0/${{ github.ref_name }}/g" pyproject.toml

      - run: |
          pip install build
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: ['build']
    environment: 'pypi'

    name: Upload release to PyPI
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
